### PR TITLE
Sfr

### PR DESCRIPTION
**Pull request by RobertTheBlair**
preview SFR changes

### CODE REVIEW

**Comment by No767** [comment]
Good luck y'all in SFR!

**Comment by RobertTheBlair** [comment]
> Good luck y'all in SFR!

I did this PR mostly as a view of what we have changed so far.

**Comment by No767** [comment]
I'll be at SFR. Thanks for letting me know about that

**Comment by RobertTheBlair** [comment]
Closing so we can have a single PR that brings in the code from SFR

**Pull request closed without merging**
